# Generated by Django 2.0.10 on 2019-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='orders', through='pizza.Quanity', to='pizza.Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingradients',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.Ingradient'),
        ),
    ]
