# Generated by Django 2.0.10 on 2019-02-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20190205_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanity',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quanities', to='pizza.Pizza', verbose_name='Pizza'),
        ),
    ]
