# Generated by Django 2.0.10 on 2019-02-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20190207_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quanity',
            old_name='quanitity',
            new_name='value',
        ),
    ]
